import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { pendingLines, deliveryStatus } from '../src/assets/js/utils/inventory.js';
const db = new PGlite();
await db.exec(`create role authenticated; create role anon; create schema auth;
 create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
 create function can_read_contract_data(text) returns boolean language sql as $$select $1='A'$$;
 create function current_profile_has_permission(text,text) returns boolean language sql as $$select coalesce(current_setting('test.permission',true),'yes')<>'no'$$;
 create table contracts(codigo text primary key,nombre text,cliente_nombre text,cliente_nit text);
 create table sedes(codigo text primary key,nombre text,contrato_codigo text,estado text);
 insert into contracts values('A','Contrato A','Cliente','123'),('B','Contrato B','Otro','456');
 insert into sedes values('S','Sede','A','activo'),('T','Otra','B','activo');`);
await db.exec(await fs.readFile(new URL('../supabase/schema_operations_phase58_inventory.sql',import.meta.url),'utf8'));
const product = async(code,contract='A') => (await db.query('select inventory_product_create($1,$2) id',[contract,{code,name:'Jabón '+code,unit:'Botella 500 ml',kind:'consumible'}])).rows[0].id;
const p = await product('J'); const p2 = await product('K');
await assert.rejects(product('X','B'),/Sin permiso/);
const post = async(type,data,parent=null,id=randomUUID(),contract='A') => {
 await db.query('select inventory_post($1,$2,$3,$4,$5)',[contract,id,type,data,parent]); return id;
};
const line = (quantity,product=p) => ({product,quantity,cost:500});
const incoming = {location:'Bodega',supplier:'Proveedor',reference:'F-1',lines:[line(10),line(4,p2)]};
const inc = await post('ingreso',incoming);
await post('ingreso',incoming,null,inc);
const balance = async() => Number((await db.query('select quantity from inventory_balances where product_id=$1',[p])).rows[0].quantity);
assert.equal(await balance(),10);
const shipment = {location:'Bodega',site:'S',recipient:'Ana',responsible:'Luis',lines:[line(8),line(4,p2)]};
await assert.rejects(post('despacho',{...shipment,lines:[line(2),line(5,p2)]}),/Existencia insuficiente/);
assert.equal(await balance(),10, 'Rollback must restore the first line if the second fails');
await assert.rejects(post('despacho',{...shipment,site:'T'}),/Sede fuera/);
await assert.rejects(post('despacho',{...shipment,lines:[line(11)]}),/Existencia insuficiente/);
assert.equal(await balance(),10);
await assert.rejects(post('ingreso',{...incoming,lines:[line(1),line(1)]}),/duplicado/);
await assert.rejects(post('ingreso',{...incoming,lines:[line(-1)]}),/Cantidad invalida/);
const draft = await post('borrador',shipment);
assert.equal(await balance(),10);
const dispatched = await post('despacho',{},draft);
assert.equal(await balance(),2);
await assert.rejects(post('despacho',{},draft),/ya despachado/);
const receipt = {receiver:'Ana',document:'123',position:'Coordinadora',accepted:true,signature:'data:image/png;base64,'+'a'.repeat(240),result:'novedades',notes:'Faltan dos botellas',lines:[line(6),line(4,p2)]};
await assert.rejects(post('recepcion',{...receipt,signature:''},dispatched),/firma/);
await assert.rejects(post('recepcion',{...receipt,lines:[line(9)]},dispatched),/superior al pendiente/);
await assert.rejects(post('recepcion',{...receipt,result:'satisfaccion'},dispatched),/parcial como novedad/);
await post('recepcion',receipt,dispatched);
assert.equal(await balance(),2); // Reception must not debit warehouse again.
await assert.rejects(post('recepcion',{...receipt,lines:[line(3)]},dispatched),/superior al pendiente/);
const last = await post('recepcion',{...receipt,result:'satisfaccion',notes:'Completo',lines:[line(2)]},dispatched);
const events = (await db.query('select * from inventory_events order by number')).rows;
assert.equal(deliveryStatus(events.find(e=>e.id===dispatched),events),'Recibido');
assert.deepEqual(pendingLines(events.find(e=>e.id===dispatched),events).map(l=>l.quantity),[0,0]);
await db.query('update inventory_products set name=$1 where id=$2',['Nuevo nombre',p]);
assert.equal((await db.query('select data from inventory_events where id=$1',[last])).rows[0].data.lines[0].name,'Jabón J');
await post('ajuste',{location:'Bodega',reference:'Conteo físico',lines:[line(-1)]});
assert.equal(await balance(),1);
await assert.rejects(post('ajuste',{location:'Bodega',reference:'Conteo',lines:[line(-2)]}),/Existencia insuficiente/);
const returnedDispatch = await post('despacho',{...shipment,lines:[line(1)]});
await post('recepcion',{...receipt,result:'rechazado',notes:'Envase dañado',lines:[line(0)]},returnedDispatch);
const returnId = await post('devolucion',{reference:'Regresó a bodega',lines:[line(1)]},returnedDispatch);
await post('devolucion',{reference:'Regresó a bodega',lines:[line(1)]},returnedDispatch,returnId);
assert.equal(await balance(),1);
await assert.rejects(post('devolucion',{reference:'Duplicada',lines:[line(1)]},returnedDispatch),/superior al pendiente/);
await assert.rejects(post('recepcion',{...receipt,lines:[line(1)]},returnedDispatch),/no tiene cantidades pendientes/);
const returnedEvents = (await db.query('select * from inventory_events')).rows;
assert.equal(deliveryStatus(returnedEvents.find(e=>e.id===returnedDispatch),returnedEvents),'Cerrado con devolución');
await db.exec("set test.permission='no'");
await assert.rejects(post('ingreso',incoming),/Sin permiso/);
await db.exec('set role authenticated');
assert.equal((await db.query('select * from inventory_events')).rows.length,0);
await assert.rejects(db.exec('delete from inventory_events'),/permission denied/);
await assert.rejects(db.exec("update inventory_balances set quantity=999"),/permission denied/);
await db.exec('reset role');
await db.exec("set test.permission='yes'");
await db.query(`insert into inventory_products(contrato_codigo,code,name,unit,kind) values('B','B','Privado','Unidad','consumible')`);
await db.exec('set role authenticated');
assert.ok((await db.query('select * from inventory_events')).rows.length>0);
assert.equal((await db.query("select * from inventory_products where contrato_codigo='B'")).rows.length,0);
await db.close();
console.log('PASS: migration, contract isolation, permissions/RLS, immutable records, stock limits, transactional rollback, retry, draft dispatch, partial receipts, signature requirement, snapshots and adjustments.');
