import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { assignmentVisitStatus } from '../src/assets/js/utils/visits.js';
const db = new PGlite();
process.on('uncaughtException', async error => { console.error(error.message, error.detail || '', error.where || '', 'position:', error.position || ''); await db.close(); process.exitCode = 1; });
const admin = '00000000-0000-0000-0000-000000000001', supervisor = '00000000-0000-0000-0000-000000000002', other = '00000000-0000-0000-0000-000000000003';
await db.exec(`create role authenticated; create role anon; create schema auth; create schema storage;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table profiles(id uuid primary key,email text,nombre text,role text,estado text,supervisor_eligible boolean,zona_codigo text,zonas_permitidas text[]);
 create table contracts(codigo text primary key,nombre text,estado text);
 create table sedes(codigo text primary key,nombre text,contrato_codigo text,zona_codigo text,estado text,qr_latitude double precision,qr_longitude double precision);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text unique);
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to authenticated;
 grant select,insert,delete on storage.objects to authenticated;
 create function can_read_contract_data(text) returns boolean language sql as $$select $1<>'B'$$;
 create function current_profile_has_permission(text,text) returns boolean language sql security definer as $$select exists(select 1 from profiles where id=auth.uid() and role='admin' and estado='activo')$$;
 create function current_supervisor_can_read_zone(text) returns boolean language sql security definer as $$select exists(select 1 from profiles where id=auth.uid() and role='supervisor' and estado='activo' and supervisor_eligible and (zona_codigo=$1 or $1=any(zonas_permitidas)))$$;
 insert into profiles values('${admin}','admin@test','Admin','admin','activo',false,null,'{}'),('${supervisor}','super@test','Ana','supervisor','activo',true,'Z1','{}'),('${other}','other@test','Luis','supervisor','activo',true,'Z2','{}');
 insert into contracts values('A','Contrato A','activo'),('B','Contrato B','activo'),('C','Contrato C','activo'),('D','Contrato D','activo');
 insert into sedes values('S1','Sede Norte','A','Z1','activo',4.7,-74.1),('S2','Sede Sur','A','Z2','activo',4.6,-74.2),('S3','Sin GPS','A','Z1','activo',null,null),('S4','Sin supervisor','A','Z3','activo',4.7,-74.1),('S5','Otro contrato','B','Z1','activo',4.7,-74.1);`);
await db.exec(await fs.readFile(new URL('../supabase/schema_operations_phase59_site_visits.sql', import.meta.url), 'utf8'));
const user = id => db.query("select set_config('test.uid',$1,false)", [id]);
const sql = async (text, values = []) => (await db.query(text, values)).rows;
const today = (await sql("select (now() at time zone 'America/Bogota')::date::text d"))[0].d;
await user(admin);
await db.exec('set role authenticated');
await db.query("select visit_save_settings('A','fortnightly',$1,200,100)", [today]);
await assert.rejects(db.query("select visit_save_settings('B','weekly',$1,200,100)", [today]), /Sin permiso/);
await assert.rejects(db.query("select visit_save_settings('C','weekly','2000-01-01',200,100)"), /periodo anterior/);
assert.equal((await sql("select visit_period_end('2026-09-03','fortnightly')::text d"))[0].d, '2026-09-16');
assert.equal((await sql("select visit_period_end('2026-09-03','weekly')::text d"))[0].d, '2026-09-09');
for (const [start, end] of [['2028-02-01','2028-02-29'],['2026-02-01','2026-02-28'],['2026-04-01','2026-04-30'],['2026-12-01','2026-12-31']]) {
  assert.equal((await sql('select visit_period_end($1,\'monthly\')::text d', [start]))[0].d, end);
}
await db.query("select visit_save_settings('C','monthly',date_trunc('month',$1::date)::date,200,100)", [today]);
await db.query("select visit_save_settings('D','weekly',$1::date+7,200,100)", [today]);
assert.equal((await sql("select * from visit_cycles where contrato_codigo='D'")).length, 0);
const cycle = (await sql("select * from visit_cycles where contrato_codigo='A'"))[0];
assert.equal((await sql('select * from visit_assignments where cycle_id=$1', [cycle.id])).length, 4);
await db.exec('select visit_sync_cycles()');
assert.equal((await sql("select * from visit_cycles where contrato_codigo='A'")).length, 1, 'Generation is idempotent');
await db.query("select visit_save_settings('A','fortnightly',$1,300,150)", [today]);
assert.equal((await sql('select radius_m from visit_cycles where id=$1', [cycle.id]))[0].radius_m, 200, 'Existing GPS criteria are frozen');
await user(supervisor);
const mine = await sql('select * from visit_assignments');
assert.deepEqual(mine.map(a => a.sede_codigo).sort(), ['S1', 'S3']);
assert.equal((await sql('select * from visit_cycles')).length, 1, 'Supervisor can read own cycle');
assert.equal((await sql('select * from visit_settings')).length, 0);
await assert.rejects(db.query("select visit_save_settings('A','weekly',$1,200,100)", [today]), /Sin permiso/);
const assignment = mine.find(a => a.sede_codigo === 'S1');
const noGps = mine.find(a => a.sede_codigo === 'S3');
const begin = (a = assignment.id, lat = 4.7, lng = -74.1, accuracy = 10, id = randomUUID()) => db.query('select visit_begin($1,$2,$3,$4,$5)', [id,a,lat,lng,accuracy]).then(() => id);
const putPhoto = async id => {
  const photo = `${supervisor}/${id}/${randomUUID()}.jpg`;
  await db.query("insert into storage.objects(bucket_id,name) values('visit-evidence',$1)", [photo]); return photo;
};
const submit = (id, photos, findings = false, description = '') => sql('select visit_submit($1,$2,$3,$4,$5,$6) status', [id,findings,description,'Recomendación','Observación',photos]);
await assert.rejects(begin(assignment.id, NaN), /GPS inválido/);
await assert.rejects(begin(assignment.id, 0, 0), /GPS inválido/);
const id = await begin();
await begin(assignment.id, 4.7, -74.1, 10, id);
await assert.rejects(submit(id, []), /1 y 6/);
await assert.rejects(submit(id, ['inexistente']), /Evidencia/);
const photo = await putPhoto(id);
await assert.rejects(submit(id, [photo], true, ''), /Describe/);
assert.equal((await submit(id, [photo]))[0].status, 'valid');
assert.equal((await submit(id, [photo], true, 'Intento de cambio'))[0].status, 'valid');
assert.equal((await sql('select findings from site_visits where id=$1', [id]))[0].findings, '', 'Submitted form is immutable');
await assert.rejects(db.query("update site_visits set status='valid' where id=$1", [id]), /permission denied/);
assert.equal((await sql('delete from storage.objects where name=$1 returning name', [photo])).length, 0, 'Submitted evidence cannot be deleted');
const far = await begin(assignment.id, 5.7, -74.1);
await assert.rejects(submit(far, [photo]), /Evidencia/);
assert.equal((await submit(far, [await putPhoto(far)]))[0].status, 'review');
const poor = await begin(assignment.id, 4.7, -74.1, 300);
assert.equal((await submit(poor, [await putPhoto(poor)]))[0].status, 'review');
const missing = await begin(noGps.id);
assert.equal((await submit(missing, [await putPhoto(missing)]))[0].status, 'review');
await assert.rejects(db.query('select visit_review($1,true,\'OK\')', [far]), /Sin permiso/);
await user(other);
await assert.rejects(begin(), /asignaciones/);
assert.equal((await sql('select * from site_visits')).length, 0);
assert.equal((await sql('select * from storage.objects')).length, 0);
await user(admin);
await assert.rejects(db.query('select visit_review($1,true,\'\')', [far]), /motivo/);
await db.query('select visit_review($1,false,\'Fuera de la sede\')', [far]);
await db.query('select visit_review($1,true,\'Evidencia verificada\')', [poor]);
await assert.rejects(db.query('select visit_review($1,true,\'Otra decisión\')', [far]), /pendiente/);
assert.equal((await sql('select * from storage.objects')).length, 4, 'Manager reads submitted evidence');
await db.exec('reset role');
await db.query("update sedes set nombre='Nuevo nombre',zona_codigo='Z2' where codigo='S1'");
assert.equal((await sql('select sede_name from visit_assignments where id=$1', [assignment.id]))[0].sede_name, 'Sede Norte');
// A cycle remains assigned to its original supervisor; new zone changes are picked up next cycle.
assert.equal((await sql('select supervisor_id from visit_assignments where id=$1', [assignment.id]))[0].supervisor_id, supervisor);
await user(supervisor);
await db.exec('set role authenticated');
const stale = await begin();
await putPhoto(stale);
await db.exec('reset role');
await db.query("update site_visits set started_at=now()-interval '31 minutes' where id=$1", [stale]);
await db.exec('set role authenticated');
await assert.rejects(submit(stale, [photo]), /venció/);
await db.exec('reset role');
await db.query("update visit_cycles set starts_on=$2::date-14,ends_on=$2::date-1 where id=$1", [cycle.id, today]);
await db.exec('set role authenticated');
await assert.rejects(begin(), /vigente/);
await db.exec('select visit_sync_cycles()');
await user(admin);
const newAssignments = await sql('select * from visit_assignments where cycle_id<>$1 and sede_codigo=\'S1\'', [cycle.id]);
assert.equal(newAssignments.length, 1);
assert.equal(newAssignments[0].supervisor_id, other, 'Next cycle picks up the new zone');
assert.equal(newAssignments[0].sede_name, 'Nuevo nombre');
assert.equal((await sql('select radius_m from visit_cycles where id=$1', [newAssignments[0].cycle_id]))[0].radius_m, 300);
assert.equal(assignmentVisitStatus(assignment, [{ assignment_id: assignment.id, status: 'valid', submitted_at: today }, { assignment_id: assignment.id, status: 'valid', submitted_at: today }], cycle), 'completed');
assert.equal(assignmentVisitStatus(assignment, [], { ends_on: '2000-01-01' }), 'overdue');
await db.close();
console.log('PASS: weekly/14-day/calendar-month cycles, leap years, scheduling, snapshots, contract/zone RLS, evidence ownership, GPS validation, immutable submission, review, expiry and duplicate-visit compliance.');
